export interface CaseDetailModel {
    clientDocumentNumber: any;
    clientMobile: any;
    clientClientCode: any;
    promotorName: any;
    promotorDocumentNumber: any;
    promotorPhone: any;
    promotorEmail: any;
    clientDocumentTypeName: any;
    closedComment: any;
    resolutionClientFavorName: any;
    affectedBranchName: any;
    receptionBranchName: any;
    claimAmount: any;
    currencyName: any;
    subject: any;
    businessOfficerUserName: any;
    callDirectionName: any;
    contactEmail: any;
    attachments: any;
    statusHistories: any;
    businessOfficer: any;
    id:                      number;
    caseStatusName:          string;
    originName:              string;
    caseOwnerUserName:       string;
    contactFullname:         string;
    contactPhone:            null;
    ticketNumber:            string;
    time:                    string;
    companyName:             string;
    contactDocumentTypeName: string;
    contactDocumentNumber:   null;
    contactClientCode:       null;
    contactBranchName:       null;
    contactMobile:           null;
    promoterFullName:        string;
    promoterPhone:           null;
    promoterDocumentNumber:  null;
    promoterEmail:           null;
    typeName:                string;
    subtypeName:             string;
    typificationName:        string;
    description:             null;
    design:                  null;
    callDirection:           string;
    updatedAt:               null;
    createdAt:               string;
    idServidesk:             null;
    resolverAreas:           any[];
    resolvers:               any[];
    businessOfficerName:     null;
    solution:                null;
    requestExtension:        string;
}
    
export interface CreateCaseModel {
    contactId:	        number,
    companyId:	        number,
    promoterId:	        number,
    callDirectionId:	number,
    typeId:	            number,
    subtypeId:	        number,
    typificationId:	    number,
    subject:	        string,
    description:	    string,
    originId:	        number,
    caseOwnerId:	    number,
    caseStatusId:	    number,
    idServidesk:	    string,
    resolutionAreaIds:	number,
    resolverIds:        number,
    businessOfficerId:	number,
    solution:	        string,
    clientComment:	    string,
    qualification:	    string,
    requestExtension:	boolean,
    attachmentFile:	    string
}
